Feat/add todo
mkh-wtag/todo-app pull request #1
Opened 2023-10-29 11:47 UTC by mkh-wtag

Add todo in the todo list

2023-10-29 12:14 UTC, hhu-wtag requested changes

2023-10-29 12:14 UTC, hhu-wtag commented on components/CreateTodo.js
> +const CreateTodo = () => {
```suggestion
const createTodo = () => {
```

2023-10-29 12:14 UTC, hhu-wtag commented on components/CreateTodo.js
> +  const createTodo = document.querySelector('.create-todo');
can we also target createTodo using an id to be consistant along with other dom targets?

2023-10-29 12:14 UTC, hhu-wtag commented on components/CreateTodo.js
> +  const cancelTodoBtn = document.querySelector('#cancelTodo');
```suggestion
  const cancelTodoButton = document.querySelector('#cancelTodo');
```

2023-10-29 12:14 UTC, hhu-wtag commented on components/CreateTodo.js
> +    const { hour, amPm } = hourCalculation();
Can we move this into an utilities file?

2023-10-29 12:14 UTC, hhu-wtag commented on components/CreateTodo.js
> +    const messageConfirmation = Toast('Please enter todo', 'error');
```suggestion
    const emptyTodoErrorNotice = Toast('Please enter todo', 'error');
```

2023-10-29 12:14 UTC, hhu-wtag commented on components/CreateTodo.js
> +    }
If no textArea value is provided we have to return early
```suggestion
    if(!textArea.value) {
      todoWrapper.appendChild(messageConfirmation);
      setTimeout(() => {
        messageConfirmation.remove();
      }, 2000)
      
      return
    }
```

2023-10-29 12:14 UTC, hhu-wtag commented on components/CreateTodo.js
In general let's not directly manipulate DOM but maintain a data structure to store all the todo info.
e.g:
```js
let todos = []

const todo = createNewTodo("New Task1", {isDone: false, isEditing: false, createdAt: getCurrentTimeFormatted()})
todos.push(todo)

// Render the list
renderTodoList()
```

2023-10-30 04:47 UTC, mkh-wtag commented on components/CreateTodo.js
Tried to fix.

2023-10-30 05:15 UTC, hhu-wtag requested changes

2023-10-30 05:15 UTC, hhu-wtag commented on index.js
> +CreateTodo();
As this is the entry point of our app, let's name it more appropriately.

```suggestion
InitializeTodoApp();
```

2023-10-30 05:15 UTC, hhu-wtag commented on components/CreateTodo.js
Can we follow a declarative approach to the architecture of the file?

Initially we have one entry point, e.g: `index.js`
```js
// index.js
import initializeTodoApp from "entry.js"

initializeTodoApp()
```

Inside `entry.js` file we have our various modules working together

```js
// entry.js
import { inputFieldElement, submitButton, cancelButton } from "../domElements.js"
import { createTodoItem, renderTodoList } from "../domActions.js"
import { isUserInputValid } from "../utilities.js"

// Global Data
let todos = []

submitButton.addEventListener("click", handleTodoSubmit)
cancelButton.addEventListener("click", handleCancel)

const handleTodoSubmit = () => {
    const content = inputFieldElement.textContent
    if(isUserInputValid(content) === false){
       return 
    }
    
    const todoItem = createTodoItem(content)
    todos.push(todoItem)

    renderTodoList(todos)
}
```

The idea of this architecture is that we delegate work to different modules and re-use functionalities when we need them.

We also need to think about the data structure of the each todo items.
A todo item is not only a text content. 
It has some state, such as, 
1. Is it in editing state
2. Is it done
3. When was it created

We can encapsulate all this logic inside an object and store them in the `todos` global array and render them whenever we need.

e.g:
```js
const todoItem = createTodo("Hello World") // {value: "Hello world", isEditing: false, isDone: false, createdAt: "Some time value"}
```

2023-11-01 04:43 UTC, hhu-wtag requested changes

2023-11-01 04:43 UTC, hhu-wtag commented on index.js
> +
We can remove the commented out code. Thanks

2023-11-01 04:43 UTC, hhu-wtag commented on index.html
> +    <!-- <div class="toast-wrapper">Hello</div> -->
ditto. 
ditto means, the similar suggestion have been given earlier. In this case, we can remove the commented out code.

2023-11-01 04:43 UTC, hhu-wtag commented on entry.js
> +
Extra whitespace can be removed. Please use prettier plugin to automatically format the code.

2023-11-01 04:43 UTC, hhu-wtag commented on entry.js
> +import { openCreateTodo, cancelTodo } from "./components/domActions.js";
They seem to import from the same file. We can use one statement.
```suggestion
import { 
  createTodoItem,
  renderTodoList,
  openCreateTodo,
  cancelTodo
 } from "./components/domActions.js";
```

2023-11-01 04:43 UTC, hhu-wtag commented on components/domActions.js
> +
ditto. Use prettier

2023-11-01 04:43 UTC, hhu-wtag commented on components/CreateTodo.js
> +  let todos = [];
We should not declare the source of data here. `todos` array should be initialised higher up the tree / as close to root as possible. 

So can we move it to `entry.js` and use it there?

```js
// entry.js file
import blah blah

// We declare the source of data
let todos = []

// We add the eventListeners
const addButton.addEventListener("click", handleAddTodo)

2023-11-01 04:43 UTC, hhu-wtag commented on components/CreateTodo.js
> +    // const todoSuccess = toast('Successfully created new todo');
Let's remove the unused comments

2023-11-01 04:43 UTC, hhu-wtag commented on components/domActions.js
> +};
`renderTodoList` is supposed to be adding actual DOM elements to the document.
Let's rename the function to `createTodoObject`
```suggestion
export const createTodoObject = () => {
  const task = textArea.value;

  const todo = {
    title: task,
    isDone: false,
    isEditing: false,
    createdAt: timeCalculation(),
  }
};
```

Notice that we wouldn't do anything else in this function following Single Responsibility principle.

2023-11-01 04:43 UTC, hhu-wtag commented on components/domActions.js
> +  const todos = renderTodoList();
```suggestion
```

2023-11-01 04:43 UTC, hhu-wtag commented on components/domActions.js
> +  todoDiv.style.background = 'linear-gradient(90deg, #daf5ea, #fff 15%)';
We'll do the mapping inside the function named `renderTodoList`
So everything in one go:
1. We add something to the inputbox and click submit
2. It triggers the eventListener we added for submit button
3. That eventListener handler function first calls `createTodoObject`
4. We then push that todo object to todos array
5. Then we call `renderTodoList` which will
    i. Map over each todo item and create DOM element using `createTodoItem` function
    ii. Then insert it to DOM

2023-11-02 04:18 UTC, hhu-wtag approved these changes
Please resolve the reviewes before merging the PR. Nice job bhai 🚀

2023-11-02 04:18 UTC, hhu-wtag commented on components/CreateTodo.js
> +  // }
Can we remove the commented out code?

2023-11-02 04:18 UTC, hhu-wtag commented on components/CreateTodo.js
> +    // todos.push(todo);
ditto

2023-11-02 04:18 UTC, hhu-wtag commented on components/CreateTodo.js
> +    todos.map((todo) => {
```suggestion
    todos.forEach((todo) => {
```

2023-11-02 04:18 UTC, hhu-wtag commented on components/CreateTodo.js
> +    // const todoSuccess = toast('Successfully created new todo');
ditto

2023-11-02 04:18 UTC, hhu-wtag commented on components/CreateTodo.js
> +    }
Let's use early return here

```suggestion
    if (!textArea.value) {
      return
    }
    
    todoDiv.append(todoHeader, todoDetails, todoActions);
    todoWrapper.append(todoDiv, todoSuccess);

    todoDiv.style.borderLeft = "5px solid #0ec277";
    todoDiv.style.background = "linear-gradient(90deg, #daf5ea, #fff 15%)";

     textArea.value = "";
     emptyNotice.remove();
     setTimeout(() => {
        todoSuccess.remove();
        todoDiv.removeAttribute("style");
      }, 2000);
```

2023-11-02 04:18 UTC, hhu-wtag commented on components/domActions.js
> +};
We don't need the `if` check as we know that `todos` is always an array
```suggestion
export const renderTodoList = () => {
  todoWrapper.innerHTML = "";
  
  todos.forEach((todo) => {
      todoWrapper.append(createTodoDomElement(todo));
   });
};
```

2023-11-02 04:18 UTC, hhu-wtag commented on components/CreateTodo.js
Maybe we don't need this file anymore as we are currently creating todo dom element in `domActions.js`?

2023-11-02 04:18 UTC, hhu-wtag commented on index.js
> +
Can we resolve this?

2023-11-02 04:18 UTC, hhu-wtag commented on utilities/createButton.js
> +};
```suggestion
const createButton = (className, idName, icon, handler) => {
  const button = document.createElement("button");
  button.className = className;
  button.id = idName;
  button.innerHTML = `<img src=./public/${icon} alt="icon" />`;
  button.addEventListener("click", handler);
  
  return button;
};
```

2023-11-02 05:10 UTC, merged